// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.3
// source: near_users.proto

package near_users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *UserLocation) Reset() {
	*x = UserLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_near_users_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLocation) ProtoMessage() {}

func (x *UserLocation) ProtoReflect() protoreflect.Message {
	mi := &file_near_users_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLocation.ProtoReflect.Descriptor instead.
func (*UserLocation) Descriptor() ([]byte, []int) {
	return file_near_users_proto_rawDescGZIP(), []int{0}
}

func (x *UserLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UserLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type NearbyUsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NearbyUsers []*User `protobuf:"bytes,1,rep,name=nearby_users,json=nearbyUsers,proto3" json:"nearby_users,omitempty"`
}

func (x *NearbyUsersResponse) Reset() {
	*x = NearbyUsersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_near_users_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NearbyUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyUsersResponse) ProtoMessage() {}

func (x *NearbyUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_near_users_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyUsersResponse.ProtoReflect.Descriptor instead.
func (*NearbyUsersResponse) Descriptor() ([]byte, []int) {
	return file_near_users_proto_rawDescGZIP(), []int{1}
}

func (x *NearbyUsersResponse) GetNearbyUsers() []*User {
	if x != nil {
		return x.NearbyUsers
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Latitude  float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Name      string  `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_near_users_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_near_users_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_near_users_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *User) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_near_users_proto protoreflect.FileDescriptor

var file_near_users_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6e, 0x65, 0x61, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x6e, 0x65, 0x61, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x48,
	0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f,
	0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c,
	0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x4a, 0x0a, 0x13, 0x4e, 0x65, 0x61, 0x72,
	0x62, 0x79, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x33, 0x0a, 0x0c, 0x6e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6e, 0x65, 0x61, 0x72, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x0b, 0x6e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x22, 0x64, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xac, 0x01, 0x0a, 0x09, 0x4e,
	0x65, 0x61, 0x72, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x4b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4e,
	0x65, 0x61, 0x72, 0x62, 0x79, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x18, 0x2e, 0x6e, 0x65, 0x61,
	0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1f, 0x2e, 0x6e, 0x65, 0x61, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x2e, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x11, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4e,
	0x65, 0x61, 0x72, 0x62, 0x79, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x18, 0x2e, 0x6e, 0x65, 0x61,
	0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1f, 0x2e, 0x6e, 0x65, 0x61, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x2e, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x20, 0x5a, 0x1e, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6e, 0x65, 0x61, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x3b, 0x6e, 0x65, 0x61, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_near_users_proto_rawDescOnce sync.Once
	file_near_users_proto_rawDescData = file_near_users_proto_rawDesc
)

func file_near_users_proto_rawDescGZIP() []byte {
	file_near_users_proto_rawDescOnce.Do(func() {
		file_near_users_proto_rawDescData = protoimpl.X.CompressGZIP(file_near_users_proto_rawDescData)
	})
	return file_near_users_proto_rawDescData
}

var file_near_users_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_near_users_proto_goTypes = []any{
	(*UserLocation)(nil),        // 0: near_users.UserLocation
	(*NearbyUsersResponse)(nil), // 1: near_users.NearbyUsersResponse
	(*User)(nil),                // 2: near_users.User
}
var file_near_users_proto_depIdxs = []int32{
	2, // 0: near_users.NearbyUsersResponse.nearby_users:type_name -> near_users.User
	0, // 1: near_users.NearUsers.GetNearbyUsers:input_type -> near_users.UserLocation
	0, // 2: near_users.NearUsers.StreamNearbyUsers:input_type -> near_users.UserLocation
	1, // 3: near_users.NearUsers.GetNearbyUsers:output_type -> near_users.NearbyUsersResponse
	1, // 4: near_users.NearUsers.StreamNearbyUsers:output_type -> near_users.NearbyUsersResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_near_users_proto_init() }
func file_near_users_proto_init() {
	if File_near_users_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_near_users_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UserLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_near_users_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*NearbyUsersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_near_users_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_near_users_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_near_users_proto_goTypes,
		DependencyIndexes: file_near_users_proto_depIdxs,
		MessageInfos:      file_near_users_proto_msgTypes,
	}.Build()
	File_near_users_proto = out.File
	file_near_users_proto_rawDesc = nil
	file_near_users_proto_goTypes = nil
	file_near_users_proto_depIdxs = nil
}
